[package]
name = "dsl"
version = "0.1.0"
authors = ["Marcelo Almeida <mgba@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustviz = { path = "../svg_generator/" }